### ISSUE TITLE
deploy key is read only

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/helm-chart#3]
@jgerardsimcock our [travis deploy key](https://github.com/RhodiumGroup/helm-chart/settings/keys) is read only. I think this is the deployment problem.

The travis build log says something about read only access to the repo when trying to deploy to gh-pages, and our key is marked as read only. It looks like you can't modify it, so you'll have to re-generate a new key with write access. I don't know how the encryption was done, so don't want to mess with a PR, but I think this may get us up and running! 😄

**Comment by bolliger32** [comment]
I think no-longer relevant
